# Generated by Django 5.0.4 on 2024-05-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
